<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <title>Cadastro de Cliente</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/static/css/app.css">
  <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
  <script src="/static/js/client/create.js" defer></script>
</head>

<body>
  <div id="app" class="form-container">
    <div class="brand">PHP Bank</div>
    <h2>Cadastro de Cliente</h2>

    <form @submit.prevent="submitForm">
      <label>Usuário</label>
      <input v-model="form.username" type="text" placeholder="Digite seu usuário" required>

      <label>Senha</label>
      <input v-model="form.password" type="password" placeholder="Crie uma senha segura" required>

      <label>Nome</label>
      <input v-model="form.name" type="text" placeholder="Seu nome completo" required>

      <label>CPF/CNPJ</label>
      <input v-model="form.cpfcnpj" type="text" placeholder="Digite seu CPF ou CNPJ" required>

      <label>Email</label>
      <input v-model="form.email" type="email" placeholder="Digite seu e-mail" required>

      <button type="submit">Cadastrar</button>

      <div class="link-container">
        <span>Já tem uma conta? </span>
        <a href="/clients/login">Faça login</a>
      </div>
    </form>


    <div v-if="success" class="status-message success">
      {{ success }}
    </div>

    <div v-if="error" class="status-message error">
      {{ error }}
    </div>

  </div>
</body>

</html>